### ISSUE TITLE
Output to Plugin operator is incorrect

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-log-collection#151]
Currently, when trying to output to a plugin it points to the entire plugin. Which is incorrect because it doesn't exist as a singular object during processing.

Example:

Config for Plugin

```
parameters:
pipeline:
 - type: noop
    id: noop1
 - type: noop
    id: noop2
```

Pipeline
```
operators:
 - type: noop
    id: noop
 - type: plugin
    id: plugin1
```

So, when trying to output to a plugin, it runs into the issue of the previous operator, `noop`, pointing to the entire plugin with an output defined as `$.plugin1`. Which, once the operators are built and flattened, doesn't exist. What it should be pointing towards is the first operator in the plugin pipeline, in this case, it should be `$.plugin1.noop1`.
