### ISSUE TITLE
filelog: Multiline merging mixes up logs from different files

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-log-collection#276]
this works fine. 
```
operators:
    - default: clean-up-log-record
      routes:
      - expr: ($$resource["k8s.namespace.name"]) matches ".*" && ($$resource["k8s.container.name"])
          == "loggen"
        output: .*_loggen
      - expr: ($$resource["k8s.container.name"]) == "loggen2"
        output: loggen2
      type: router
    - combine_field: log
      id: .*_loggen
      is_first_entry: '($.log) matches "num: \\d+0\\s"'
      output: clean-up-log-record
      type: recombine
    - combine_field: log
      id: loggen2
      is_first_entry: '($$.log) matches "num: \\d+0\\s"'
      output: clean-up-log-record
      type: recombine
    - id: clean-up-log-record
      ops:
      - move:
          from: log
          to: $
      type: restructure
```
because `loggen` container and `loggen2` container is separately routed to its own `recombine` operator. 
but with configurations like this one
```
operators:
    - default: clean-up-log-record
      routes:
      - expr: ($$resource["k8s.namespace.name"]) matches ".*" && ($$resource["k8s.container.name"])
          == "loggen.*"
        output: .*_loggen.*
      type: router
    - combine_field: log
      id: .*_loggen.*
      is_first_entry: '($.log) matches "num: \\d+0\\s"'
      output: clean-up-log-record
      type: recombine
    - id: clean-up-log-record
      ops:
      - move:
          from: log
          to: $
      type: restructure
```
they get mixed up

**Comment by jsirianni** [comment]
Do both containers log to the same file? Can you provide input and output samples?

**Comment by rockb1017** [comment]
sorry for late reply. it is logging to a separate files. I can't reproduce it so i think it was a misconfiguration. Thank you.

**Comment by rockb1017** [comment]
reopening this. similar issue is reported. https://github.com/signalfx/splunk-otel-collector-chart/issues/309

**Comment by rockb1017** [comment]
I also see it now. 
![image](https://user-images.githubusercontent.com/12387289/142696135-af1dc5c7-35b3-4e97-9303-4b21ed475a3f.png)

`num: 100061 | loggen-tjh79 | 2021-11-19T21:23:21.643933 | rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
` this is from log generator.  i have it merging at every 10 events.
but `2021/11/19 21:23:22 EPS: 0` this like is from another pod

**Comment by rockb1017** [comment]
for more context, this works fine. 
```
operators:
    - default: clean-up-log-record
      routes:
      - expr: ($$resource["k8s.namespace.name"]) matches ".*" && ($$resource["k8s.container.name"])
          == "loggen"
        output: .*_loggen
      - expr: ($$resource["k8s.container.name"]) == "loggen2"
        output: loggen2
      type: router
    - combine_field: log
      id: .*_loggen
      is_first_entry: '($.log) matches "num: \\d+0\\s"'
      output: clean-up-log-record
      type: recombine
    - combine_field: log
      id: loggen2
      is_first_entry: '($$.log) matches "num: \\d+0\\s"'
      output: clean-up-log-record
      type: recombine
    - id: clean-up-log-record
      ops:
      - move:
          from: log
          to: $
      type: restructure
```
because `loggen` container and `loggen2` container is separately routed to its own `recombine` operator. 
but with configurations like this one
```
operators:
    - default: clean-up-log-record
      routes:
      - expr: ($$resource["k8s.namespace.name"]) matches ".*" && ($$resource["k8s.container.name"])
          == "loggen.*"
        output: .*_loggen.*
      type: router
    - combine_field: log
      id: .*_loggen.*
      is_first_entry: '($.log) matches "num: \\d+0\\s"'
      output: clean-up-log-record
      type: recombine
    - id: clean-up-log-record
      ops:
      - move:
          from: log
          to: $
      type: restructure
```
they get mixed up
