### ISSUE TITLE
unable to parse using regex or json parser operator

### ISSUE THREAD

**Issue by navneet1075** [open-telemetry/opentelemetry-log-collection#316]
i am creating a custom otel contrib processor  in which first i have to read from the filelog receiver and then do some processing on top of it .

i am using the config like this for regex parser  . taken from the example from regex parse documentation page. 

```
receivers:
  filelog:
    include:
      - audit/simple.json
    start_at: beginning
    include_file_path: true
    includ_file_name: true
    operators:
    - type: regex_parser
      parse_from: message
      regex: '^Host=(?P<host>[^,]+), Type=(?P<type>.*)$'
```

the file that i am using is this (audit/simple.json):  

```
{
  "timestamp": "",
  "body": {
    "message": "Host=127.0.0.1, Type=HTTP"
  }
}
```

expectation:
the file is parsed properly.

actual :   

i get below error while parsing 

```
 Started watching file   {"kind": "receiver", "name": "filelog", "operator_id": "$.file_input", "operator_type": "file_input", "path": "audit/simple.json"}
2021-11-27T12:28:36.209+0100    error   Failed to process entry {"kind": "receiver", "name": "filelog", "operator_id": "$.regex_parser", "operator_type": "regex_parser", "error": {"description": "Entry is missing the expected parse_from field.", "suggestion": "Ensure that all incoming entries contain the parse_from field.", "details": {"parse_from": "message"}}, "action": "send", "entry": {"timestamp":"2021-11-27T12:28:36.209817+01:00","body":"{","attributes":{"file.name":"simple.json","file.path":"audit/simple.json"},"severity":0}}
```

i dont know what i am doing wrong . i tried several examples in the docs page but it does not work.  i am using the latest version (v0.40.0) of filelogreceiver. 

the code is here : https://github.com/navneet1075/otlppbprocessor
