### ISSUE TITLE
syslog_input should embed syslog_parser inline

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#34]
Since this operator is first and foremost a syslog operator, users should not need to specify `syslog` at two different levels, as is necessary with the current implementation.

Current:
```
type: syslog
syslog:
  protocol: rfc5424
tcp:
  listen_address: ...
```
 
Syslog Inline:
```
type: syslog
protocol: rfc5424
tcp:
  listen_address: ...
```
