### ISSUE TITLE
Remove "write_to" configuration setting from input operators

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#408]
All input operators currently support a `write_to` option, which allows users to specify the field to which an entry is initialized. I believe this setting is redundant, and slightly detrimental to both performance and maintenance of the library. Since we are about to make a set of additional breaking changes, I propose that this feature should also be removed.

Here's an example usage of the field:

```yaml
  - type: file_input
    include:
      - ./*.log
    write_to: body.foo
```

Entries read through this operator would place the log contents under `body.foo`, instead of just `body`.

This can instead be accomplished with the following configuration:
```yaml
  - type: file_input
    include:
      - ./*.log
  - type: move
    from: body
    to: body.foo
```

The setting has a slightly negative performance impact, because every single log entry that is created must take into consideration where the log entry should be written. Without this, we can simply set the value to `entry.Body` without regard for configuration.
