### ISSUE TITLE
CSV parser is too eager when reading files being written to

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-log-collection#423]
See this configuration fragment:
```
receivers:
    filelog:
        include: [ /output/*.csv ]
        start_at: beginning
        multiline:
            line_start_pattern: "^\"[^\"]"
        operators:
            # remove the header line
            -   id: remove_header
                type: filter
                expr: '$$body matches "^AuthorID,Author,Date,Content,Attachments,Reactions$"'
                output: csv
            # parse each line as a record
            -   id: csv
                type: csv_parser
                header: AuthorID,Author,Date,Content,Attachments,Reactions
                timestamp:
                    parse_from: Date
                    layout_type: epoch
                    layout: s
                    preserve: true
```

(excerpted from https://github.com/splunk/splunk-addon-for-discord/blob/main/otel-collector-config.yml)

When writing a CSV file, the CSV parser will execute aggressively against the entry and will fail to process CSV entries.
