### ISSUE TITLE
Remove "metadata" operator

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-log-collection#428]
As mentioned in #410, I believe the `metadata` operator should be removed. It assumes that `attributes` and `resource` are flat maps. This will be problematic in the near future.

The `add` operator can easily support the same use cases.

Example usage of `metadata`:
```yaml
- type: metadata
  attributes:
    environment: production
  resource:
    cluster: blue
```

The same can be achieved with `add`:
```yaml
- type: add
  field: attributes.environment
  value: production
- type: add
  field: resource.cluster
  value: blue
```
